language: node_js
sudo: false
node_js:
  - "iojs"
before_script:
  - npm install -g grunt-cli gitbook-cli
  - gitbook install book
after_success:
  - |
    if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ]; then
        echo "$SSH_KEY" | base64 --decode > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval `ssh-agent`
        ssh-add ~/.ssh/id_rsa
        ./scripts/publish-pages.sh
    fi
matrix:
  fast_finish: true
notifications:
  email: false
