#!/bin/bash

# Execute a command with a timeout
# License: LGPLv2
# http://www.pixelbeat.org/scripts/timeout

cleanup()
{
    trap - ALRM               #reset handler to default
    kill -ALRM $a 2>/dev/null #stop timer subshell if running
    kill $! 2>/dev/null &&    #kill last job
      exit 124                #exit with 124 if it was running
}

watchit()
{
    trap "cleanup" ALRM
    sleep $1& wait
    kill -ALRM $$
}

timeout()
{
    watchit $1& a=$!         #start the timeout
    shift                    #first param was timeout for sleep
    trap "cleanup" ALRM INT  #cleanup after timeout
    "$@"& wait $!; RET=$?    #start the job wait for it and save its return value
    kill -ALRM $a            #send ALRM signal to watchit
    wait $a                  #wait for watchit to finish cleanup
    return $RET                #return the value    
}

timeout 5 wget -O- -T 5 http://example.com/ >/dev/null 2>&1
if [ $? == 0 ]; then
	echo 'you are connected to the Internet.'
else
	echo 'error: you are NOT connected to the Internet!'
	echo 'use "solo-utils tunnel-start" to connect.'
	exit 1
fi
