#!/bin/bash

echo 'disabling output of video...'
init 2

sv once /opt/solo-utils/video-service
sv term /opt/solo-utils/video-service

echo 'restoring video patch...'
cp /usr/bin/sn_master_snd.original /usr/bin/sn_master_snd
chmod +x /usr/bin/sn_master_snd

# This is probably a bit heavy.
sleep 1
sv term /opt/solo-utils/video-service
sleep 1
sv term /opt/solo-utils/video-service
sleep 1
sv term /opt/solo-utils/video-service
sleep 1
sv term /opt/solo-utils/video-service
sleep 1
sv term /opt/solo-utils/video-service
sleep 1
sv term /opt/solo-utils/video-service
sleep 1
sv term /opt/solo-utils/video-service
sleep 1
sv term /opt/solo-utils/video-service
sleep 1
sv term /opt/solo-utils/video-service
sleep 1
sv kill /opt/solo-utils/video-service

# disable v4l2loopback
modprobe -r v4l2loopback

echo 'restarting video...'

# This is pretty heavy too.
init 4
sleep 1
init 4
echo 'done.'
