#!/bin/bash

cd $(dirname $0)

FIFO=gst.fifo
CONF=$(cat ./output-pipeline | xargs)

modprobe mxc_v4l2_capture
modprobe -r v4l2loopback
modprobe v4l2loopback exclusive_caps=0,0 video_nr=1,2

rm -f $FIFO
mkfifo $FIFO

gst-launch tvsrc device=/dev/video0 ! mfw_ipucsc ! tee name=vid \
    vid. ! $CONF ! v4l2sink device=/dev/video1 \
    vid. ! queue ! v4l2sink device=/dev/video2 2> $FIFO &
TAIL_PID=$!

# Poll video output
(cat $FIFO | while read LOGLINE; do
    [[ "$LOGLINE" == *"CRITICAL"* ]] && kill -9 $TAIL_PID && break
done) &
READ_PID=$!

trap "kill -9 $READ_PID; kill -9 $TAIL_PID" SIGINT SIGHUP SIGTERM
wait

echo 'killing video feed...'

