#!/bin/bash

SEEDS=$({ cat ~/.seed-hosts 2>/dev/null || echo '3dr.com'; } | tr '\n' ',' | sed 's/,$//')
echo $SEEDS
exec /opt/sshuttle/sshuttle -H --dns -r pc 0/0 -vv -x 10.1.1.100/24 --seed-hosts $SEEDS 2>&1
