#!/bin/bash

ssh -q -oBatchMode=yes pc "exit 0"

if [ $? -ne 0 ]; then
    echo 'You must set up an SSH tunnel to your host PC first.'
    echo 'Run this in your terminal:'
    echo "    echo '$(cat ~/.ssh/id_rsa.pub)' >> ~/.ssh/authorized_keys"
    echo ''
    read -p "Host username (whoami): " username

    cat <<EOF > ~/.ssh/config
Host pc
    HostName 10.1.1.100
    Port 22
    User $username
EOF

    ssh pc "echo 'setup succeeded!'" || { echo 'failed.' && exit 1; }
fi

sv status /opt/sdg/tunnel-service 2>/dev/null
if [ $? -ne 0 ]; then
    runsv /opt/sdg/tunnel-service >/dev/null 2>&1 &
fi
sv up /opt/sdg/tunnel-service
echo 'tunnelling service started.'
